{% set name = "seaborn-image" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seaborn-image-{{ version }}.tar.gz
  sha256: aeb77f62f74f0ab50d8e70b132a2ae461aefaab7e523187fd45447f893b836fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.8
  run:
    - python >=3.8
    - importlib_metadata
    - matplotlib-base
    - matplotlib-scalebar
    - palettable
    - pooch
    - scikit-image >=0.17.2
    - scipy

test:
  imports:
    - seaborn_image

about:
  home: https://github.com/SarthakJariwala/seaborn-image
  summary: Attractive, descriptive and effective image visualization with seaborn-like API built on top of matplotlib
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SarthakJariwala
